### PR TITLE
Use all python code if possible

### PR DESCRIPTION
**Pull request by LyzardKing**
Hi! I just "merged" the shell code in python,
I also added the success/failure dialogs as proper modal dialogs.
If possible I'd like to add a cli option, again in python..
If this is an acceptable PR and option let me know!

Thanks for the program!
I needed something like this but I never bothered to write anything with a gui.

### CODE REVIEW

**Comment by abhishekpc** [comment]
@LyzardKing Thanks for the changes. We'll run some tests on our end (to avoid surprises) and merge the PR after that.

**Comment by LyzardKing** [comment]
Great! I was thinking about adding automated tests (i.e. a pdf that can succeed, and one that is known to fail) on github actions/travis..
What tests are you running on your end?

**Comment by abhishekpc** [comment]
@LyzardKing That is already on our to-do list. For now, it is manual testing with files with spaces/quotes in name, files that are known to have bigger size when compressed etc.

Since I never coded in Python (I haven't coded anything in last few years), it will take me some time and effort to create the tests in Python. Panos is also new to Python.

If you have suggestions for the unit tests (or is it called something else), please let us know.

**Comment by LyzardKing** [comment]
Yes, I made a very basic pdf test.. I can open another PR (since setting up the tests made me split slightly the ui and the logic..).

**Pull request merged**
